platform :ios, '6.1'

target :GHUnitTest, :exclusive => true do
       pod 'GHUnitIOS', '~> 0.5.5'
end

target :KiwiTest, :exclusive => true do
   pod 'Kiwi'
end

target :jankenKIF, :exclusive => true do
   pod 'KIF'
end